version: 2.1

executors:
  android-executor:
    docker:
      - image: cimg/android:2025.02
    working_directory: ~/project

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Grant execute permission to Gradle wrapper
          command: chmod +x android/gradlew
      - run:
          name: Build Android App
          command: |
            cd android
            ./gradlew assembleDebug
      - store_artifacts:
          path: android/app/build/outputs/apk/debug/app-debug.apk
          destination: app-debug.apk

workflows:
  version: 2
  build_android:
    jobs:
      - build
